server:
  port: 8002

# Management #
management:
  server:  
    ssl:
      enabled: false
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,refresh,env

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
  file:
    path: ./logs
    name: rest-server.log

